development:
  adapter: postgresql
  database: noremediation
  username: natashagreen
  password:
  host: localhost

production:
  adapter: postgresql
  database: noremediation
  username: natashagreen
  password:
  host: localhost