development:
  adapter: postgresql
  database: <%= ENV['DATABASE_URL'] %>
  username: natashagreen
  password:
  host: localhost

production:
  adapter: postgresql
  database: <%= ENV['DATABASE_URL'] %>
  username: natashagreen
  password:
  host: localhost